/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewGame.java
 *
 * Created on 7.12.2011, 15:51:31
 */
package cz.mgn.go.menu;

import cz.mgn.go.game.GameStarter;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author filcicyr
 */
public class NewGame extends javax.swing.JFrame {

    /** Creates new form NewGame */
    public NewGame() {
        initComponents();
        init2();
    }

    protected void init2() {
        String[] sizes = new String[20];
        for (int i = 0; i < sizes.length; i++) {
            sizes[i] = "" + (i + 5) + "x" + (i + 5);
        }
        cPlaygroundSize.setModel(new DefaultComboBoxModel(sizes));
    }

    protected void mainMenu() {
        dispose();
        new MainMenu().setVisible(true);
    }
    /**
     * starts GameStarter, with inputed parameters
     */
    protected void startGame() {
        String playerOne = cPlayer1Nick.getText();
        String playerTwo = cPlayer2Nick.getText();
        if (playerOne.length() > 0 && playerTwo.length() > 0) {
            String s = cPlaygroundSize.getSelectedItem().toString();
            s = s.substring(0, s.indexOf("x"));
            int playgroundSize = Integer.parseInt(s);
            GameStarter.startGame(playgroundSize, playerOne, playerTwo);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cPlaygroundSize = new javax.swing.JComboBox();
        cPlayer1Nick = new javax.swing.JTextField();
        cPlayer2Nick = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Playground size:");

        jLabel2.setText("Player 1 nick:");

        jLabel3.setText("Player 2 nick:");

        cPlaygroundSize.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "9x9", "13x13", "19x19" }));
        cPlaygroundSize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cPlaygroundSizeActionPerformed(evt);
            }
        });

        cPlayer1Nick.setText("player1");

        cPlayer2Nick.setText("player2");

        jPanel1.setBackground(javax.swing.UIManager.getDefaults().getColor("window"));
        jPanel1.setLayout(new java.awt.GridLayout());

        jButton1.setText("START GAME");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);

        jButton2.setText("MAIN MENU");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cPlayer1Nick, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                            .addComponent(cPlaygroundSize, 0, 246, Short.MAX_VALUE)
                            .addComponent(cPlayer2Nick, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cPlaygroundSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cPlayer1Nick, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cPlayer2Nick, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cPlaygroundSizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cPlaygroundSizeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cPlaygroundSizeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        startGame();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        mainMenu();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new NewGame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cPlayer1Nick;
    private javax.swing.JTextField cPlayer2Nick;
    private javax.swing.JComboBox cPlaygroundSize;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
